### ISSUE TITLE
merge unicorn and lobsters roles?

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters-ansible#27]
@jstoja wrote in #25:

> I was thinking that, to me, it makes very little sense to split unicorn and lobsters (I think they should be merged to form 1 more coherent role). What do you think about it?

I didn't want this question to get lost after that PR was merged. I don't have an immediate answer, but after #23 the two seem more closely linked. And it seems very unlikely that Lobsters needs another host in the next few years to, say run background jobs and not a webserver or something else requiring the codebase but not unicorn.

@alanpost, when you're not busy with the [migration later this week](https://lobste.rs/s/twmful/upcoming_downtime_for_maintenance_2018), any thoughts?

**Comment by alanpost** [comment]
Both unicorn and lobsters use the same host group.  If it makes sense to everyone to merge them that's reasonable enough.

I would keep them separate if I was doing significant custom work for each--I had them originally separate because I tend to lift roles from one playbook to another and I need "unicorn" in places I don't need "lobsters."  That reasoning doesn't apply inside a single playbook however.  If we're using a unicorn package or otherwise have minimal configuration overhead and you'd like to merge these roles I agree with @pushcx that we certainly won't create problems doing so.

**Comment by pushcx** [comment]
We've had enough hassles with unicorn specifically and lobsters cron/backup jobs specifically that I see these as two different things.

I'm creating a ticket for the removal of RedHat, though.
