### ISSUE TITLE
Why Brave is blocked?

### ISSUE THREAD

**Issue by norbertpy** [lobsters/lobsters-ansible#45]
Any specific reason why Brave is blocked as per [block "Brave" cryptocurrency scam](https://github.com/lobsters/lobsters-ansible/blob/4f15109aa790befab3153006fde0ae2fe98e9c92/roles/nginx/files/production/nginx/sites-available/lobste.rs#L61)?

Thanks.

**Comment by pushcx** [comment]
Fraud. The added UI to the browser to claim users could pay individual site creators who'd signed up, but had  scraped the names and photos of site creators who'd never heard of them. Brave planned to take the payments after they were unclaimed for 90 days. When caught, they claimed the funds were held "in escrow" but later admitted there were holding the funds themselves. Story broke here: https://news.ycombinator.com/item?id=18734999

The UI went beyond confusing into deliberately deceptive, and inventing a financial partner made their bad faith unambiguous to me. This seemed the only way to effectively opt out of them claiming to fundraise on the site's behalf.

From their issue tracker, they've [targeted us specifically](https://github.com/brave/brave-browser/issues/4641) in their plan to circumvent blocks. This linked issue isn't implemented, but they must have reverted their user agent to pretend to be Chrome again because I haven't had ICO bros in my Twitter mentions for a while. I don't know if they're actively scamming visitors now but would appreciate hearing about it if so. I hate that we have to burn precious volunteer developer time dealing with spam and cryptocurrency scams, but that's the internet sometimes. :(

**Comment by pushcx** [comment]
This topic seems to be warming up this weekend so I looked again at Brave.

Since this issue was posted, Brave has [injected their affiliate code](https://news.sophos.com/en-us/2020/06/09/brave-ceo-apologises-for-adding-affiliate-links-to-urls/) into links and [leaked DNS](https://www.coindesk.com/tech/2021/02/22/brave-browser-was-exposing-addresses-in-tor-mode-for-months) when supposedly using Tor. I was unaware that they had previously [whitelisted Facebook and Twitter trackers](https://news.sophos.com/en-us/2019/02/12/privacy-browser-braves-user-concern-over-facebook-whitelist/) while claiming to block trackers.

While the fundraising confiscation scam has ended, the pattern of behavior is clear. I still don't want to burn time and energy dealing with scammers so I'm not scheduling dev work on this, but if options for blocking Brave land in my lap I'm happy to add them. I added a note with contact info to the [issue in our other tracker](https://github.com/lobsters/lobsters/issues/761) and I'm going to lock the issues to avoid accidental leaks.
